-- MySQL Script generated by MySQL Workbench
-- 07/29/19 17:16:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema e-commerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `e-commerce` ;

-- -----------------------------------------------------
-- Schema e-commerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e-commerce` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
SHOW WARNINGS;
USE `e-commerce` ;

-- -----------------------------------------------------
-- Table `e-commerce`.`faqs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e-commerce`.`faqs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `e-commerce`.`faqs` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `question` VARCHAR(120) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `answer` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `e-commerce`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e-commerce`.`roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `e-commerce`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `e-commerce`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e-commerce`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `e-commerce`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(120) NOT NULL COMMENT '',
  `lastname` VARCHAR(120) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `password` VARCHAR(120) NOT NULL COMMENT '',
  `avatar` VARCHAR(200) NOT NULL COMMENT '',
  `type` VARCHAR(4) NOT NULL COMMENT '',
  `nroDoc` INT(11) NOT NULL COMMENT '',
  `phone` INT(11) NULL DEFAULT NULL COMMENT '',
  `address` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `role_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `e-commerce`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `user_role_idx` ON `e-commerce`.`users` (`role_id` ASC)  COMMENT '';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `e-commerce`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e-commerce`.`categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `e-commerce`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(120) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `e-commerce`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e-commerce`.`products` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `e-commerce`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `description` VARCHAR(255) NOT NULL COMMENT '',
  `dimension` DECIMAL(4,2) NULL DEFAULT NULL COMMENT '',
  `category_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `price` DECIMAL(8,2) NOT NULL COMMENT '',
  `stock` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `e-commerce`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `product_category_idx` ON `e-commerce`.`products` (`category_id` ASC)  COMMENT '';

SHOW WARNINGS;

/* Adding initial roles */
INSERT INTO `e-commerce`.`roles` (`id`, `name`) VALUES ('1', 'admin');
INSERT INTO `e-commerce`.`roles` (`id`, `name`) VALUES ('2', 'user');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
